import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/widgets.dart' as pw;
import 'package:http/http.dart' as http;
import 'package:farmly/models/new_detection_result.dart';
import 'package:farmly/core/api_config.dart';

/// Generates a professional PDF report from crop disease detection results.
class ReportPdfGenerator {
  /// Generate a PDF report and return the raw bytes.
  static Future<Uint8List> generateReport({
    required LeafDetectionResult detection,
    AdvisoryResult? advisory,
    required String language,
  }) async {
    final pdf = pw.Document();

    // Try to load images from server
    Uint8List? originalImageBytes;
    Uint8List? annotatedImageBytes;

    if (detection.originalImageUrl.isNotEmpty) {
      originalImageBytes = await _downloadImage(detection.originalImageUrl);
    }
    if (detection.annotatedImageUrl.isNotEmpty) {
      annotatedImageBytes = await _downloadImage(detection.annotatedImageUrl);
    }

    // Color scheme
    final primaryColor = PdfColor.fromHex('#0D631B');
    final accentColor = PdfColor.fromHex('#2E7D32');
    final warningColor = PdfColor.fromHex('#6E5100');
    final errorColor = PdfColor.fromHex('#BA1A1A');
    final lightGreen = PdfColor.fromHex('#E8F5E9');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(primaryColor, accentColor),
        footer: (context) => _buildFooter(context, primaryColor),
        build: (context) => [
          // ── Title ──
          pw.SizedBox(height: 8),
          pw.Center(
            child: pw.Text(
              'Crop Disease Analysis Report',
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
                color: primaryColor,
              ),
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Center(
            child: pw.Text(
              'Generated by Farmly AI • ${DateTime.now().toString().substring(0, 16)}',
              style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
          ),
          pw.SizedBox(height: 16),
          pw.Divider(color: primaryColor, thickness: 2),
          pw.SizedBox(height: 16),

          // ── Status Badge ──
          _buildStatusBadge(detection, primaryColor, warningColor, errorColor),
          pw.SizedBox(height: 16),

          // ── Image ──
          if (originalImageBytes != null) ...[
            pw.Center(
              child: pw.Column(children: [
                pw.Container(
                  height: 200,
                  width: double.infinity,
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: primaryColor, width: 2),
                    borderRadius: pw.BorderRadius.circular(8),
                  ),
                  child: pw.ClipRRect(
                    horizontalRadius: 8,
                    verticalRadius: 8,
                    child: pw.Image(pw.MemoryImage(originalImageBytes), fit: pw.BoxFit.cover),
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text('Uploaded Image', style: pw.TextStyle(fontSize: 9, color: primaryColor)),
              ]),
            ),
            pw.SizedBox(height: 20),
          ],

          // ── Detection Details Table ──
          _buildSectionTitle('Detection Details', primaryColor),
          pw.SizedBox(height: 8),
          _buildDetailsTable(detection, primaryColor, lightGreen),
          pw.SizedBox(height: 16),

          // ── Top Predictions ──
          if (detection.topPredictions.isNotEmpty) ...[
            _buildSectionTitle('Top Predictions', primaryColor),
            pw.SizedBox(height: 8),
            _buildPredictionsTable(detection.topPredictions, primaryColor, lightGreen),
            pw.SizedBox(height: 16),
          ],

          // ── Advisory Section ──
          if (advisory != null && !advisory.isEmpty) ...[
            _buildSectionTitle('AI-Generated Advisory ($language)', primaryColor),
            pw.SizedBox(height: 8),

            if (advisory.summary.isNotEmpty) ...[
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  color: lightGreen,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Text(advisory.summary, style: const pw.TextStyle(fontSize: 11, lineSpacing: 4)),
              ),
              pw.SizedBox(height: 12),
            ],

            if (advisory.symptoms.isNotEmpty) ...[
              _buildSubSection('Symptoms', advisory.symptoms, errorColor),
              pw.SizedBox(height: 10),
            ],

            if (advisory.possibleCauses.isNotEmpty) ...[
              _buildSubSection('Possible Causes', advisory.possibleCauses, warningColor),
              pw.SizedBox(height: 10),
            ],

            if (advisory.recommendedActions.isNotEmpty) ...[
              _buildNumberedSection('Recommended Actions', advisory.recommendedActions, primaryColor),
              pw.SizedBox(height: 10),
            ],

            if (advisory.prevention.isNotEmpty) ...[
              _buildSubSection('Prevention', advisory.prevention, accentColor),
              pw.SizedBox(height: 10),
            ],

            // ── Safety Note ──
            if (advisory.safetyNote.isNotEmpty) ...[
              pw.SizedBox(height: 8),
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('#FFF3E0'),
                  borderRadius: pw.BorderRadius.circular(6),
                  border: pw.Border.all(color: warningColor, width: 0.5),
                ),
                child: pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('⚠ ', style: pw.TextStyle(fontSize: 12, color: warningColor)),
                    pw.Expanded(
                      child: pw.Text(
                        advisory.safetyNote,
                        style: pw.TextStyle(fontSize: 9, fontStyle: pw.FontStyle.italic, color: warningColor, lineSpacing: 3),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ],
        ],
      ),
    );

    // Return bytes instead of saving to file for Web compatibility
    return await pdf.save();
  }

  // ── Header ──
  static pw.Widget _buildHeader(PdfColor primary, PdfColor accent) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 8),
      decoration: pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: primary, width: 2)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Row(children: [
            pw.Text('🌱 ', style: const pw.TextStyle(fontSize: 18)),
            pw.Text('Farmly', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: primary)),
          ]),
          pw.Text('AI Crop Disease Detection', style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500)),
        ],
      ),
    );
  }

  // ── Footer ──
  static pw.Widget _buildFooter(pw.Context context, PdfColor primary) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'This report is AI-generated. Always consult local agricultural experts.',
            style: pw.TextStyle(fontSize: 7, color: PdfColors.grey500, fontStyle: pw.FontStyle.italic),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(fontSize: 8, color: primary),
          ),
        ],
      ),
    );
  }

  // ── Status Badge ──
  static pw.Widget _buildStatusBadge(
    LeafDetectionResult detection, PdfColor primary, PdfColor warning, PdfColor error,
  ) {
    final color = detection.isSuccess ? primary : detection.isUncertain ? warning : error;
    final label = detection.isSuccess ? 'DISEASE DETECTED' : detection.isUncertain ? 'UNCERTAIN RESULT' : 'NO LEAF DETECTED';

    return pw.Center(
      child: pw.Container(
        padding: const pw.EdgeInsets.symmetric(horizontal: 20, vertical: 8),
        decoration: pw.BoxDecoration(
          color: color,
          borderRadius: pw.BorderRadius.circular(20),
        ),
        child: pw.Text(label, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
      ),
    );
  }

  // ── Section Title ──
  static pw.Widget _buildSectionTitle(String title, PdfColor color) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: pw.BoxDecoration(
        color: color,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Text(title, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
    );
  }

  // ── Details Table ──
  static pw.Widget _buildDetailsTable(LeafDetectionResult d, PdfColor primary, PdfColor bg) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: {
        0: const pw.FlexColumnWidth(1.5),
        1: const pw.FlexColumnWidth(2.5),
      },
      children: [
        _tableRow('Crop Detected', d.crop, bg),
        _tableRow('Crop Confidence', '${(d.cropConfidence * 100).toStringAsFixed(1)}%', PdfColors.white),
        _tableRow('Disease', d.disease, bg),
        _tableRow('Disease Confidence', '${(d.diseaseConfidence * 100).toStringAsFixed(1)}%', PdfColors.white),
        _tableRow('Status', d.status.toUpperCase().replaceAll('_', ' '), bg),
      ],
    );
  }

  static pw.TableRow _tableRow(String label, String value, PdfColor bg) {
    return pw.TableRow(
      decoration: pw.BoxDecoration(color: bg),
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(label, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
        ),
      ],
    );
  }

  // ── Predictions Table ──
  static pw.Widget _buildPredictionsTable(List<PredictionItem> preds, PdfColor primary, PdfColor bg) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: {
        0: const pw.FixedColumnWidth(30),
        1: const pw.FlexColumnWidth(3),
        2: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: primary),
          children: [
            _headerCell('#'),
            _headerCell('Disease'),
            _headerCell('Confidence'),
          ],
        ),
        ...preds.asMap().entries.map((e) => pw.TableRow(
          decoration: pw.BoxDecoration(color: e.key.isEven ? bg : PdfColors.white),
          children: [
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text('${e.key + 1}', style: const pw.TextStyle(fontSize: 10))),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(e.value.label, style: const pw.TextStyle(fontSize: 10))),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text('${(e.value.confidence * 100).toStringAsFixed(1)}%', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold))),
          ],
        )),
      ],
    );
  }

  static pw.Widget _headerCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
    );
  }

  // ── Bullet List ──
  static pw.Widget _buildSubSection(String title, List<String> items, PdfColor dotColor) {
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Text(title, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 4),
      ...items.map((item) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 3, left: 8),
        child: pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Container(
            width: 5, height: 5,
            margin: const pw.EdgeInsets.only(top: 4),
            decoration: pw.BoxDecoration(shape: pw.BoxShape.circle, color: dotColor),
          ),
          pw.SizedBox(width: 8),
          pw.Expanded(child: pw.Text(item, style: const pw.TextStyle(fontSize: 10, lineSpacing: 3))),
        ]),
      )),
    ]);
  }

  // ── Numbered List ──
  static pw.Widget _buildNumberedSection(String title, List<String> items, PdfColor numColor) {
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Text(title, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 4),
      ...items.asMap().entries.map((e) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 4, left: 8),
        child: pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Container(
            width: 16, height: 16,
            decoration: pw.BoxDecoration(shape: pw.BoxShape.circle, color: numColor),
            child: pw.Center(child: pw.Text('${e.key + 1}', style: pw.TextStyle(fontSize: 8, color: PdfColors.white, fontWeight: pw.FontWeight.bold))),
          ),
          pw.SizedBox(width: 8),
          pw.Expanded(child: pw.Text(e.value, style: const pw.TextStyle(fontSize: 10, lineSpacing: 3))),
        ]),
      )),
    ]);
  }

  // ── Download Image ──
  static Future<Uint8List?> _downloadImage(String relativeUrl) async {
    try {
      final url = '${ApiConfig.baseUrl}$relativeUrl';
      final response = await http.get(Uri.parse(url)).timeout(const Duration(seconds: 10));
      if (response.statusCode == 200) return response.bodyBytes;
    } catch (_) {}
    return null;
  }
}
