import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
  static const List<Locale> supportedLocales = [Locale('mr'), Locale('hi'), Locale('en')];

  String translate(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Farmly',
      'welcome': 'Welcome to Farmly',
      'choose_language': 'Choose your language',
      'continue_btn': 'Continue',
      'marathi': 'Marathi',
      'hindi': 'Hindi',
      'english': 'English',
      'welcome_back': 'Welcome Back',
      'phone_number': 'Phone Number',
      'send_otp': 'Send OTP',
      'enter_otp': 'Enter OTP',
      'verify': 'Verify',
      'guest_login': 'Continue as Guest',
      'start_scanning': 'Start Scanning Crops',
      'home': 'Home',
      'scan': 'Scan',
      'community': 'Community',
      'profile': 'Profile',
      'my_profile': 'My Profile',
      'saved_diagnoses': 'Saved Diagnoses',
      'weather_failed': 'Could not fetch weather data',
      'scan_crop': 'Scan Crop',
      'weather': 'Weather',
      'crop_tips': 'Crop Tips',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'hello_farmer': 'Hello, Farmer',
      'scan_instruction': 'Show the leaf clearly',
      'take_photo': 'Take Photo',
      'gallery': 'Choose from Gallery',
      'analyzing': 'Analyzing...',
      'detection_result': 'Detection Result',
      'severity': 'Severity',
      'treatment': 'Treatment',
      'causes': 'Causes',
      'prevention': 'Prevention',
      'ai_analysis': 'AI Analysis',
      'view_details': 'View Details',
      'scan_again': 'Scan Again',
      'sugarcane': 'Sugarcane',
      'cotton': 'Cotton',
      'soybean': 'Soybean',
      'rice': 'Rice',
      'grape': 'Grape',
      'none': 'None',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'critical': 'Critical',
      'notifications': 'Notifications',
      'no_notifications': 'No notifications yet',
      'settings': 'Settings',
      'language': 'Language',
      'location': 'Location',
      'about': 'About',
      'logout': 'Logout',
      'login_first': 'Please login first',
      'disease_info': 'Disease Information',
      'ask_community': 'Ask Community',
      'scan_history': 'Scan History',
      'no_history': 'No scan history yet',
      'save_diagnosis': 'Save Diagnosis',
      'diagnosis_saved': 'Diagnosis Saved ✅',
      'saving': 'Saving...',
      // Multi-image scan
      'quick_scan': 'Quick Scan',
      'advanced_scan': 'Advanced Scan',
      'add_more_images': 'Add More Photos',
      'images_selected': 'photos selected',
      'max_images': 'Maximum 5 photos allowed',
      'remove_image': 'Remove',
      'multi_scan_tip': 'Take 3-5 photos from different angles for better accuracy',
      // Validation
      'validating': 'Validating image...',
      'not_plant': 'Not a plant image',
      'image_blurry': 'Image is blurry',
      'image_dark': 'Image is too dark',
      'image_bright': 'Image is overexposed',
      'retake_photo': 'Retake Photo',
      'low_confidence': 'Low confidence detection',
      'retake_suggestion': 'Try taking a clearer, closer photo of the leaf',
      'image_valid': 'Image validated ✓',
      'image_warning': 'Image quality warning',
      // Healthy
      'healthy_leaf': 'Healthy Leaf! 🌿',
      'no_disease': 'No disease detected. Your crop looks healthy!',
      // Weather
      'weather_dashboard': 'Weather Dashboard',
      'forecast_7day': '7-Day Forecast',
      'rain_chance': 'Rain Chance',
      'agri_advisory': 'Agricultural Advisory',
      'spray_timing': 'Spray Timing',
      'disease_risk': 'Disease Risk',
      'live': 'Live',
      'temperature': 'Temperature',
      'precipitation': 'Precipitation',
      // Recommendations
      'recommendations': 'Recommendations',
      'next_7_day_care': 'Next 7-Day Care Plan',
      'watering_advice': 'Watering Advice',
      'fertilizer_caution': 'Fertilizer Caution',
      'disease_spread_risk': 'Disease Spread Risk',
      'medicine_availability': 'Medicine Availability',
      // Processing
      'uploading_image': 'Uploading image...',
      'analyzing_crop': 'Analyzing crop...',
      'identifying_disease': 'Identifying disease...',
      'preparing_results': 'Preparing results...',
      'upload': 'Upload',
      'analyze': 'Analyze',
      'identify': 'Identify',
      'done': 'Done',
      'cancel': 'Cancel',
      // Errors
      'connection_error': 'Connection error. Please check your internet.',
      'detection_failed': 'Detection failed. Using offline mode.',
      'offline_mode': 'Offline Mode',
      'try_again': 'Try Again',
      'go_home': 'Go Home',
      'no_results': 'No results available',
      // Profile
      'edit_profile': 'Edit Profile',
      'name': 'Name',
      'change_language': 'Change Language',
      'set_location': 'Set Location',
      'my_scans': 'My Scans',
      'total_scans': 'Total Scans',
      // Location
      'allow_location': 'Allow location access',
      'location_subtitle': 'For localized weather, crop tips, and nearby farmers.',
      'detecting_location': 'Detecting location...',
      'allow': 'Allow',
      'skip': 'Skip',
      'location_denied': 'Location permission denied',
      'location_set': 'Location set',
      // History
      'history': 'History',
      'recent_scans': 'Recent Scans',
      'view_all': 'View All',
      'no_scans_yet': 'No scans yet. Scan your first crop!',
      'delete_scan': 'Delete Scan',
      // Share
      'share_result': 'Share Result',
      'share_with_farmer': 'Share with another farmer',
      // Detection V2
      'ai_crop_analysis': 'AI-Based Crop Disease Analysis',
      'analysis_result': 'Analysis Result',
      'crop_localized_yolo': 'Crop leaf localized by YOLOv8',
      'disease_classifier_label': 'Disease analyzed using a pretrained plant disease classifier',
      'top_predictions': 'Top Predictions',
      'advisory_language': 'Advisory Language:',
      'ai_advisory': 'AI-Generated Advisory',
      'advisory_unavailable': 'Advisory unavailable',
      'analyze_another': 'Analyze Another Image',
      'result_unclear': 'Result needs a clearer image',
      'possible_matches': 'Possible Matches',
      'photo_tips': 'Photo Tips',
      'tip_daylight': 'Take photo in daylight',
      'tip_one_leaf': 'Keep one leaf in focus',
      'tip_no_shadows': 'Avoid heavy shadows',
      'tip_both_sides': 'Capture both sides if symptoms are visible',
      'no_leaf_detected': 'No Crop Leaf Detected',
      'image_not_analyzed': 'Image Could Not Be Analyzed',
      'upload_another': 'Upload Another Image',
      'try_another_image': 'Try Another Image',
      'checking_quality': 'Checking image quality...',
      'uploading_scanning': 'Uploading & scanning...',
      'detecting_disease': 'Detecting crop leaf & disease...',
      'analyzing_crop_v2': 'Analyzing Crop',
      'detection_failed_v2': 'Detection Failed',
      'symptoms': 'Symptoms',
      'possible_causes': 'Possible Causes',
      'recommended_actions': 'Recommended Actions',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'tutorial_1_title': 'Snap Crop Photos',
      'tutorial_1_desc': 'Take a clear picture of any crop leaf showing symptoms of disease or pest infestation.',
      'tutorial_2_title': 'Instant AI Diagnosis',
      'tutorial_2_desc': 'Our advanced AI models analyze leaf symptoms within seconds to identify crop diseases accurately.',
      'tutorial_3_title': 'Expert Treatment Plan',
      'tutorial_3_desc': 'Get customized organic and chemical treatment advice in your local language to save your crops.',
    },
    'mr': {
      'app_name': 'फार्मली',
      'welcome': 'फार्मलीमध्ये आपले स्वागत',
      'choose_language': 'तुमची भाषा निवडा',
      'continue_btn': 'पुढे',
      'marathi': 'मराठी',
      'hindi': 'हिंदी',
      'english': 'इंग्रजी',
      'welcome_back': 'पुन्हा स्वागत',
      'phone_number': 'फोन नंबर',
      'send_otp': 'OTP पाठवा',
      'enter_otp': 'OTP टाका',
      'verify': 'सत्यापित करा',
      'guest_login': 'अतिथी म्हणून पुढे जा',
      'start_scanning': 'पीक स्कॅनिंग सुरू करा',
      'home': 'मुख्यपृष्ठ',
      'scan': 'स्कॅन',
      'community': 'समुदाय',
      'profile': 'प्रोफाइल',
      'my_profile': 'माझी प्रोफाइल',
      'saved_diagnoses': 'जतन केलेली निदाने',
      'weather_failed': 'हवामान डेटा मिळवता आला नाही',
      'scan_crop': 'पीक स्कॅन करा',
      'weather': 'हवामान',
      'crop_tips': 'पीक टिप्स',
      'humidity': 'आर्द्रता',
      'wind': 'वारा',
      'hello_farmer': 'नमस्कार, शेतकरी',
      'scan_instruction': 'पान स्पष्टपणे दाखवा',
      'take_photo': 'फोटो काढा',
      'gallery': 'गॅलरीतून निवडा',
      'analyzing': 'विश्लेषण करत आहे...',
      'detection_result': 'तपासणी निकाल',
      'severity': 'तीव्रता',
      'treatment': 'उपचार',
      'causes': 'कारणे',
      'prevention': 'प्रतिबंध',
      'ai_analysis': 'AI विश्लेषण',
      'view_details': 'तपशील पहा',
      'scan_again': 'पुन्हा स्कॅन करा',
      'sugarcane': 'ऊस',
      'cotton': 'कापूस',
      'soybean': 'सोयाबीन',
      'rice': 'भात',
      'grape': 'द्राक्ष',
      'none': 'नाही',
      'low': 'कमी',
      'medium': 'मध्यम',
      'high': 'जास्त',
      'critical': 'गंभीर',
      'notifications': 'सूचना',
      'no_notifications': 'अद्याप कोणत्याही सूचना नाहीत',
      'settings': 'सेटिंग्ज',
      'language': 'भाषा',
      'location': 'स्थान',
      'about': 'बद्दल',
      'logout': 'बाहेर पडा',
      'login_first': 'कृपया प्रथम लॉगिन करा',
      'disease_info': 'रोग माहिती',
      'ask_community': 'समुदायाला विचारा',
      'scan_history': 'स्कॅन इतिहास',
      'no_history': 'अद्याप स्कॅन इतिहास नाही',
      'save_diagnosis': 'निदान जतन करा',
      'diagnosis_saved': 'निदान जतन झाले ✅',
      'saving': 'जतन करत आहे...',
      'quick_scan': 'जलद स्कॅन',
      'advanced_scan': 'प्रगत स्कॅन',
      'add_more_images': 'आणखी फोटो जोडा',
      'images_selected': 'फोटो निवडले',
      'max_images': 'कमाल ५ फोटो',
      'remove_image': 'काढा',
      'multi_scan_tip': 'चांगल्या अचूकतेसाठी वेगवेगळ्या कोनातून ३-५ फोटो घ्या',
      'validating': 'प्रतिमा तपासत आहे...',
      'not_plant': 'हे पिकाचे चित्र नाही',
      'image_blurry': 'प्रतिमा धूसर आहे',
      'image_dark': 'प्रतिमा खूप गडद आहे',
      'image_bright': 'प्रतिमा खूप उजळ आहे',
      'retake_photo': 'पुन्हा फोटो काढा',
      'low_confidence': 'कमी विश्वासार्हता',
      'retake_suggestion': 'पानाचा अधिक स्पष्ट आणि जवळचा फोटो घ्या',
      'image_valid': 'प्रतिमा तपासली ✓',
      'image_warning': 'प्रतिमा गुणवत्ता इशारा',
      'healthy_leaf': 'निरोगी पान! 🌿',
      'no_disease': 'कोणताही रोग आढळला नाही. तुमचे पीक निरोगी दिसते!',
      'weather_dashboard': 'हवामान डॅशबोर्ड',
      'forecast_7day': '७ दिवसांचा अंदाज',
      'rain_chance': 'पावसाची शक्यता',
      'agri_advisory': 'कृषी सल्ला',
      'spray_timing': 'फवारणीची वेळ',
      'disease_risk': 'रोगाचा धोका',
      'live': 'लाइव्ह',
      'temperature': 'तापमान',
      'precipitation': 'पर्जन्यमान',
      'recommendations': 'शिफारसी',
      'next_7_day_care': 'पुढील ७ दिवसांचे नियोजन',
      'watering_advice': 'पाणी व्यवस्थापन सल्ला',
      'fertilizer_caution': 'खत वापर सूचना',
      'disease_spread_risk': 'रोग प्रसाराचा धोका',
      'medicine_availability': 'औषध उपलब्धता',
      'uploading_image': 'प्रतिमा अपलोड होत आहे...',
      'analyzing_crop': 'पीक विश्लेषण होत आहे...',
      'identifying_disease': 'रोग ओळखत आहे...',
      'preparing_results': 'निकाल तयार होत आहे...',
      'upload': 'अपलोड',
      'analyze': 'विश्लेषण',
      'identify': 'ओळख',
      'done': 'पूर्ण',
      'cancel': 'रद्द करा',
      'connection_error': 'कनेक्शन त्रुटी. कृपया इंटरनेट तपासा.',
      'detection_failed': 'तपासणी अयशस्वी. ऑफलाइन मोड.',
      'offline_mode': 'ऑफलाइन मोड',
      'try_again': 'पुन्हा प्रयत्न करा',
      'go_home': 'मुख्यपृष्ठावर जा',
      'no_results': 'निकाल उपलब्ध नाहीत',
      'edit_profile': 'प्रोफाइल संपादित करा',
      'name': 'नाव',
      'change_language': 'भाषा बदला',
      'set_location': 'स्थान सेट करा',
      'my_scans': 'माझे स्कॅन',
      'total_scans': 'एकूण स्कॅन',
      'allow_location': 'स्थान वापरण्यास परवानगी द्या',
      'location_subtitle': 'स्थानिक हवामान, पीक टिप्स आणि जवळचे शेतकरी पाहण्यासाठी.',
      'detecting_location': 'स्थान शोधत आहे...',
      'allow': 'परवानगी द्या',
      'skip': 'वगळा',
      'location_denied': 'स्थान परवानगी नाकारली',
      'location_set': 'स्थान सेट केले',
      'history': 'इतिहास',
      'recent_scans': 'अलीकडील स्कॅन',
      'view_all': 'सर्व पहा',
      'no_scans_yet': 'अद्याप स्कॅन नाही. पहिले पीक स्कॅन करा!',
      'delete_scan': 'स्कॅन हटवा',
      'share_result': 'निकाल शेअर करा',
      'share_with_farmer': 'दुसऱ्या शेतकऱ्याशी शेअर करा',
      // Detection V2
      'ai_crop_analysis': 'AI-आधारित पीक रोग विश्लेषण',
      'analysis_result': 'विश्लेषण निकाल',
      'crop_localized_yolo': 'YOLOv8 ने पीक पान शोधले',
      'disease_classifier_label': 'प्रशिक्षित वनस्पती रोग वर्गीकरणाद्वारे रोग विश्लेषित',
      'top_predictions': 'शीर्ष अंदाज',
      'advisory_language': 'सल्ला भाषा:',
      'ai_advisory': 'AI-निर्मित सल्ला',
      'advisory_unavailable': 'सल्ला उपलब्ध नाही',
      'analyze_another': 'दुसरी प्रतिमा विश्लेषित करा',
      'result_unclear': 'स्पष्ट प्रतिमा आवश्यक आहे',
      'possible_matches': 'संभाव्य जुळणी',
      'photo_tips': 'फोटो टिप्स',
      'tip_daylight': 'दिवसाच्या प्रकाशात फोटो घ्या',
      'tip_one_leaf': 'एक पान फोकसमध्ये ठेवा',
      'tip_no_shadows': 'जास्त सावली टाळा',
      'tip_both_sides': 'लक्षणे दिसत असल्यास दोन्ही बाजू कॅप्चर करा',
      'no_leaf_detected': 'पीक पान आढळले नाही',
      'image_not_analyzed': 'प्रतिमा विश्लेषित होऊ शकली नाही',
      'upload_another': 'दुसरी प्रतिमा अपलोड करा',
      'try_another_image': 'दुसरी प्रतिमा वापरा',
      'checking_quality': 'प्रतिमा गुणवत्ता तपासत आहे...',
      'uploading_scanning': 'अपलोड आणि स्कॅन होत आहे...',
      'detecting_disease': 'पीक पान आणि रोग शोधत आहे...',
      'analyzing_crop_v2': 'पीक विश्लेषण',
      'detection_failed_v2': 'तपासणी अयशस्वी',
      'symptoms': 'लक्षणे',
      'possible_causes': 'संभाव्य कारणे',
      'recommended_actions': 'शिफारस केलेल्या कृती',
      'skip': 'वगळा',
      'next': 'पुढे',
      'get_started': 'सुरू करा',
      'tutorial_1_title': 'पिकाचा फोटो काढा',
      'tutorial_1_desc': 'रोग किंवा किडीची लक्षणे दिसणाऱ्या पिकाच्या पानाचा स्पष्ट फोटो काढा.',
      'tutorial_2_title': 'त्वरित AI निदान',
      'tutorial_2_desc': 'आमचे प्रगत AI तंत्रज्ञान काही सेकंदात पानांचे विश्लेषण करून अचूक रोग ओळखते.',
      'tutorial_3_title': 'तज्ज्ञांचा उपचार सल्ला',
      'tutorial_3_desc': 'तुमचे पीक वाचवण्यासाठी स्थानिक भाषेत सानुकूलित सेंद्रिय आणि रासायनिक उपचारांचा सल्ला मिळवा.',
    },
    'hi': {
      'app_name': 'फार्मली',
      'welcome': 'फार्मली में आपका स्वागत है',
      'choose_language': 'अपनी भाषा चुनें',
      'continue_btn': 'आगे बढ़ें',
      'marathi': 'मराठी',
      'hindi': 'हिंदी',
      'english': 'अंग्रेज़ी',
      'welcome_back': 'वापसी पर स्वागत',
      'phone_number': 'फोन नंबर',
      'send_otp': 'OTP भेजें',
      'enter_otp': 'OTP दर्ज करें',
      'verify': 'सत्यापित करें',
      'guest_login': 'अतिथि के रूप में जारी रखें',
      'start_scanning': 'फसल स्कैनिंग शुरू करें',
      'home': 'होम',
      'scan': 'स्कैन',
      'community': 'समुदाय',
      'profile': 'प्रोफ़ाइल',
      'my_profile': 'मेरी प्रोफ़ाइल',
      'saved_diagnoses': 'सहेजे गए निदान',
      'weather_failed': 'मौसम डेटा प्राप्त नहीं हो सका',
      'scan_crop': 'फसल स्कैन करें',
      'weather': 'मौसम',
      'crop_tips': 'फसल सुझाव',
      'humidity': 'नमी',
      'wind': 'हवा',
      'hello_farmer': 'नमस्ते, किसान',
      'scan_instruction': 'पत्ती स्पष्ट रूप से दिखाएं',
      'take_photo': 'फोटो लें',
      'gallery': 'गैलरी से चुनें',
      'analyzing': 'विश्लेषण हो रहा है...',
      'detection_result': 'पहचान परिणाम',
      'severity': 'गंभीरता',
      'treatment': 'उपचार',
      'causes': 'कारण',
      'prevention': 'रोकथाम',
      'ai_analysis': 'AI विश्लेषण',
      'view_details': 'विवरण देखें',
      'scan_again': 'फिर से स्कैन करें',
      'sugarcane': 'गन्ना',
      'cotton': 'कपास',
      'soybean': 'सोयाबीन',
      'rice': 'धान',
      'grape': 'अंगूर',
      'none': 'कोई नहीं',
      'low': 'कम',
      'medium': 'मध्यम',
      'high': 'अधिक',
      'critical': 'गंभीर',
      'notifications': 'सूचनाएं',
      'no_notifications': 'अभी कोई सूचना नहीं',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'location': 'स्थान',
      'about': 'बारे में',
      'logout': 'लॉगआउट',
      'login_first': 'कृपया पहले लॉगिन करें',
      'disease_info': 'रोग जानकारी',
      'ask_community': 'समुदाय से पूछें',
      'scan_history': 'स्कैन इतिहास',
      'no_history': 'अभी तक कोई स्कैन इतिहास नहीं',
      'save_diagnosis': 'निदान सहेजें',
      'diagnosis_saved': 'निदान सहेजा गया ✅',
      'saving': 'सहेज रहे हैं...',
      'quick_scan': 'त्वरित स्कैन',
      'advanced_scan': 'उन्नत स्कैन',
      'add_more_images': 'और फोटो जोड़ें',
      'images_selected': 'फोटो चयनित',
      'max_images': 'अधिकतम 5 फोटो',
      'remove_image': 'हटाएं',
      'multi_scan_tip': 'बेहतर सटीकता के लिए विभिन्न कोणों से 3-5 फोटो लें',
      'validating': 'छवि सत्यापित हो रही है...',
      'not_plant': 'यह फसल की छवि नहीं है',
      'image_blurry': 'छवि धुंधली है',
      'image_dark': 'छवि बहुत अंधेरी है',
      'image_bright': 'छवि बहुत चमकीली है',
      'retake_photo': 'फिर से फोटो लें',
      'low_confidence': 'कम विश्वसनीयता',
      'retake_suggestion': 'पत्ती की अधिक स्पष्ट और करीबी तस्वीर लें',
      'image_valid': 'छवि सत्यापित ✓',
      'image_warning': 'छवि गुणवत्ता चेतावनी',
      'healthy_leaf': 'स्वस्थ पत्ती! 🌿',
      'no_disease': 'कोई रोग नहीं मिला। आपकी फसल स्वस्थ दिखती है!',
      'weather_dashboard': 'मौसम डैशबोर्ड',
      'forecast_7day': '7 दिन का पूर्वानुमान',
      'rain_chance': 'बारिश की संभावना',
      'agri_advisory': 'कृषि सलाह',
      'spray_timing': 'छिड़काव का समय',
      'disease_risk': 'रोग का खतरा',
      'live': 'लाइव',
      'temperature': 'तापमान',
      'precipitation': 'वर्षा',
      'recommendations': 'सिफारिशें',
      'next_7_day_care': 'अगले 7 दिन की देखभाल योजना',
      'watering_advice': 'सिंचाई सलाह',
      'fertilizer_caution': 'उर्वरक सावधानी',
      'disease_spread_risk': 'रोग प्रसार जोखिम',
      'medicine_availability': 'दवा उपलब्धता',
      'uploading_image': 'छवि अपलोड हो रही है...',
      'analyzing_crop': 'फसल का विश्लेषण हो रहा है...',
      'identifying_disease': 'रोग की पहचान हो रही है...',
      'preparing_results': 'परिणाम तैयार हो रहे हैं...',
      'upload': 'अपलोड',
      'analyze': 'विश्लेषण',
      'identify': 'पहचान',
      'done': 'पूर्ण',
      'cancel': 'रद्द करें',
      'connection_error': 'कनेक्शन त्रुटि। कृपया इंटरनेट जांचें।',
      'detection_failed': 'पहचान विफल। ऑफ़लाइन मोड।',
      'offline_mode': 'ऑफ़लाइन मोड',
      'try_again': 'पुनः प्रयास करें',
      'go_home': 'होम पर जाएं',
      'no_results': 'कोई परिणाम उपलब्ध नहीं',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'name': 'नाम',
      'change_language': 'भाषा बदलें',
      'set_location': 'स्थान सेट करें',
      'my_scans': 'मेरे स्कैन',
      'total_scans': 'कुल स्कैन',
      'allow_location': 'स्थान एक्सेस की अनुमति दें',
      'location_subtitle': 'स्थानीय मौसम, फसल सुझाव और आस-पास के किसानों के लिए।',
      'detecting_location': 'स्थान का पता लगा रहे हैं...',
      'allow': 'अनुमति दें',
      'skip': 'छोड़ें',
      'location_denied': 'स्थान अनुमति अस्वीकृत',
      'location_set': 'स्थान सेट किया गया',
      'history': 'इतिहास',
      'recent_scans': 'हाल के स्कैन',
      'view_all': 'सभी देखें',
      'no_scans_yet': 'अभी तक कोई स्कैन नहीं। अपनी पहली फसल स्कैन करें!',
      'delete_scan': 'स्कैन हटाएं',
      'share_result': 'परिणाम साझा करें',
      'share_with_farmer': 'दूसरे किसान के साथ साझा करें',
      // Detection V2
      'ai_crop_analysis': 'AI-आधारित फसल रोग विश्लेषण',
      'analysis_result': 'विश्लेषण परिणाम',
      'crop_localized_yolo': 'YOLOv8 द्वारा फसल पत्ती पहचानी गई',
      'disease_classifier_label': 'प्रशिक्षित पौधा रोग वर्गीकरण द्वारा रोग विश्लेषित',
      'top_predictions': 'शीर्ष अनुमान',
      'advisory_language': 'सलाह भाषा:',
      'ai_advisory': 'AI-निर्मित सलाह',
      'advisory_unavailable': 'सलाह उपलब्ध नहीं',
      'analyze_another': 'एक और छवि विश्लेषित करें',
      'result_unclear': 'स्पष्ट छवि की आवश्यकता है',
      'possible_matches': 'संभावित मिलान',
      'photo_tips': 'फोटो टिप्स',
      'tip_daylight': 'दिन के प्रकाश में फोटो लें',
      'tip_one_leaf': 'एक पत्ती को फोकस में रखें',
      'tip_no_shadows': 'ज़्यादा छाया से बचें',
      'tip_both_sides': 'लक्षण दिखे तो दोनों ओर कैप्चर करें',
      'no_leaf_detected': 'फसल पत्ती नहीं मिली',
      'image_not_analyzed': 'छवि विश्लेषित नहीं हो सकी',
      'upload_another': 'दूसरी छवि अपलोड करें',
      'try_another_image': 'दूसरी छवि आज़माएं',
      'checking_quality': 'छवि गुणवत्ता जाँच रहे हैं...',
      'uploading_scanning': 'अपलोड और स्कैन हो रहा है...',
      'detecting_disease': 'फसल पत्ती और रोग पहचान रहे हैं...',
      'analyzing_crop_v2': 'फसल विश्लेषण',
      'detection_failed_v2': 'पहचान विफल',
      'symptoms': 'लक्षण',
      'possible_causes': 'संभावित कारण',
      'recommended_actions': 'अनुशंसित कार्रवाइयाँ',
      'skip': 'छोड़ें',
      'next': 'आगे',
      'get_started': 'शुरू करें',
      'tutorial_1_title': 'फसल की फोटो लें',
      'tutorial_1_desc': 'रोग या कीट के लक्षण दिखाने वाले किसी भी फसल के पत्ते की स्पष्ट फोटो लें।',
      'tutorial_2_title': 'तुरंत AI निदान',
      'tutorial_2_desc': 'हमारे उन्नत AI मॉडल कुछ ही सेकंड में लक्षणों का विश्लेषण करके सटीक रोग की पहचान करते हैं।',
      'tutorial_3_title': 'विशेषज्ञ उपचार योजना',
      'tutorial_3_desc': 'अपनी फसल को बचाने के लिए अपनी स्थानीय भाषा में जैविक और रासायनिक उपचार सलाह प्राप्त करें।',
    },
  };
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'mr', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
